//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChessMaker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public Game()
        {
            this.GamePlayers = new HashSet<GamePlayer>();
            this.Moves = new HashSet<Move>();
        }
    
        public int ID { get; set; }
        public int VariantVersionID { get; set; }
        public byte StatusID { get; set; }
        public Nullable<int> NextUserID { get; set; }
        public int NextMoveNumber { get; set; }
    
        public virtual ICollection<GamePlayer> GamePlayers { get; set; }
        public virtual GameStatus GameStatus { get; set; }
        public virtual User User { get; set; }
        public virtual VariantVersion VariantVersion { get; set; }
        public virtual ICollection<Move> Moves { get; set; }
    }
}
