//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChessMaker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.GamePlayers = new HashSet<GamePlayer>();
            this.Games = new HashSet<Game>();
            this.Variants = new HashSet<Variant>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<GamePlayer> GamePlayers { get; set; }
        public virtual ICollection<Game> Games { get; set; }
        public virtual ICollection<Variant> Variants { get; set; }
    }
}
