//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChessMaker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VariantVersion
    {
        public VariantVersion()
        {
            this.Games = new HashSet<Game>();
            this.Variants = new HashSet<Variant>();
        }
    
        public int ID { get; set; }
        public int VariantID { get; set; }
        public short Number { get; set; }
        public System.DateTime LastModified { get; set; }
        public string Definition { get; set; }
    
        public virtual ICollection<Game> Games { get; set; }
        public virtual ICollection<Variant> Variants { get; set; }
    }
}
