//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChessMaker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Variant
    {
        public Variant()
        {
            this.AllVersions = new HashSet<VariantVersion>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int CreatedByID { get; set; }
        public Nullable<int> PublicVersionID { get; set; }
        public byte PlayerCount { get; set; }
    
        public virtual User CreatedBy { get; set; }
        public virtual VariantVersion PublicVersion { get; set; }
        public virtual ICollection<VariantVersion> AllVersions { get; set; }
    }
}
